# docker compose file for database
version: "3.9"

services:
   postgres-db:
      build: ./pg_db
      container_name: postgres-db
      ports:
         - "5432:5432"
      volumes:
        - /var/lib/postgresql/data

   go-api: 
      build: ./backend
      container_name: go-api
      ports:
         - "3000:3000"
      depends_on:
         - postgres-db
      volumes:
        - ./backend:/app

   svelte-app:
      build: ./frontend
      container_name: svelte-app
      ports:
         - "8080:3000"
      depends_on:
         - go-api
      volumes:
        - ./frontend:/app
    
  